services:
  app:
    container_name: app # nama container yang ingin dibuat
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "goapp:1.0.0" # hasil build image namanya ini
    environment:
      - "APP_PORT=8080"
    ports:
      - "8080:8080"