FROM alpine:3

LABEL author="Hafiz Caniago"
LABEL company="Self Employed" website="https://www.hafizcaniago.my.id/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"