services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hafigo
      MONGO_INITDB_ROOT_PASSWORD: hafigo
      MONGO_INITDB_DATABASE: admin