services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hafigo
      MONGO_INITDB_ROOT_PASSWORD: hafigo
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db" # Bind mount to a local directory
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hafigo
      MONGO_INITDB_ROOT_PASSWORD: hafigo
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        source: "./data-mongo2" # Bind mount to a local directory
        target: "/data/db" # this is the default location for MongoDB data
        read_only: false